name: Test and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Install and test
    runs-on: ubuntu-latest
    strategy:
      matrix: #You can specify an array of versions that the tests will run against.
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Run tests
      - run: npm run test
        env:
          CI: true
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'tribe-video-api' #Must be unique in Heroku
          heroku_email: 'younesaitmha@gmail.com'
          branch: 'main'
          usedocker: true
        env:
          HD_NODE_ENV: 'production'
          #HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_PORT: 8080
