#tests.yml
name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Install and test
    runs-on: ubuntu-latest
    strategy:
      matrix: #You can specify an array of versions that the tests will run against.
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Run tests
      - run: npm run test
        env:
          CI: true
